package frc.robot.Sensors;

public class LEDs {
    public static final double Fixed_Palette_Pattern_Rainbow_Rainbow = -0.99; //RainbowPalettePatternDensitySpeedBrightness11005
    public static final double Fixed_Palette_Pattern_Rainbow_Party = -0.97; //PartyPalettePatternDensitySpeedBrightness21015
    public static final double Fixed_Palette_Pattern_Rainbow_Ocean = -0.95; //OceanPalettePatternDensitySpeedBrightness31025
    public static final double Fixed_Palette_Pattern_Rainbow_Lava = -0.93; //LavePalettePatternDensitySpeedBrightness41035
    public static final double Fixed_Palette_Pattern_Rainbow_Forest = -0.91; //ForestPalettePatternDensitySpeedBrightness51045
    public static final double Fixed_Palette_Pattern_Rainbow_with_Glitter_Pattern_Density_Speed_Brightness = -0.89; //61055
    public static final double Fixed_Palette_Pattern_Confetti_Pattern_Density_Speed_Brightness = -0.87; //71065
    public static final double Fixed_Palette_Pattern_Shot_Red = -0.85; //Red--Brightness81075
    public static final double Fixed_Palette_Pattern_Shot_Blue = -0.83; //Blue--Brightness91085
    public static final double Fixed_Palette_Pattern_Shot_White = -0.81; //White--Brightness101095
    public static final double Fixed_Palette_Pattern_Sinelon_Rainbow = -0.79; //RainbowPalettePatternDensitySpeedBrightness111105
    public static final double Fixed_Palette_Pattern_Sinelon_Party = -0.77; //PartyPalettePatternDensitySpeedBrightness121115
    public static final double Fixed_Palette_Pattern_Sinelon_Ocean = -0.75; //OceanPalettePatternDensitySpeedBrightness131125
    public static final double Fixed_Palette_Pattern_Sinelon_Lava = -0.73; //LavaPalettePatternDensitySpeedBrightness141135
    public static final double Fixed_Palette_Pattern_Sinelon_Forest = -0.71; //ForestPalettePatternDensitySpeedBrightness151145
    public static final double Fixed_Palette_Pattern_Beats_per_Minute_Rainbow = -0.69; //RainbowPalettePatternDensitySpeedBrightness161155
    public static final double Fixed_Palette_Pattern_Beats_per_Minute_Party = -0.67; //PartyPalettePatternDensitySpeedBrightness171165
    public static final double Fixed_Palette_Pattern_Beats_per_Minute_Ocean = -0.65; //OceanPalettePatternDensitySpeedBrightness181175
    public static final double Fixed_Palette_Pattern_Beats_per_Minute_Lava = -0.63; //LavaPalettePatternDensitySpeedBrightness191185
    public static final double Fixed_Palette_Pattern_Beats_per_Minute_Forest = -0.61; //ForestPalettePatternDensitySpeedBrightness201195
    public static final double Fixed_Palette_Pattern_Fire_Medium = -0.59; //Medium--Brightness211205
    public static final double Fixed_Palette_Pattern_Fire_Large = -0.57; //Large--Brightness221215
    public static final double Fixed_Palette_Pattern_Twinkles_Rainbow = -0.55; //RainbowPalette--Brightness231225
    public static final double Fixed_Palette_Pattern_Twinkles_Party = -0.53; //PartyPalette--Brightness241235
    public static final double Fixed_Palette_Pattern_Twinkles_Ocean = -0.51; //OceanPalette--Brightness251245
    public static final double Fixed_Palette_Pattern_Twinkles_Lava = -0.49; //LavaPalette--Brightness261255
    public static final double Fixed_Palette_Pattern_Twinkles_Forest = -0.47; //ForestPalette--Brightness271265
    public static final double Fixed_Palette_Pattern_Color_Waves_Rainbow = -0.45; //RainbowPalette--Brightness281275
    public static final double Fixed_Palette_Pattern_Color_Waves_Party = -0.43; //PartyPalette--Brightness291285
    public static final double Fixed_Palette_Pattern_Color_Waves_Ocean = -0.41; //OceanPalette--Brightness301295
    public static final double Fixed_Palette_Pattern_Color_Waves_Lava = -0.39; //LavaPalette--Brightness311305
    public static final double Fixed_Palette_Pattern_Color_Waves_Forest = -0.37; //ForestPalette--Brightness321315
    public static final double Fixed_Palette_Pattern_Larson_Scanner_Red = -0.35; //RedPatternWidthSpeedBrightness331325
    public static final double Fixed_Palette_Pattern_Larson_Scanner_Gray = -0.33; //GrayPatternWidthSpeedBrightness341335
    public static final double Fixed_Palette_Pattern_Light_Chase_Red = -0.31; //RedDimmingSpeedBrightness351345
    public static final double Fixed_Palette_Pattern_Light_Chase_Blue = -0.29; //BlueDimmingSpeedBrightness361355
    public static final double Fixed_Palette_Pattern_Light_Chase_Gray = -0.27; //GrayDimmingSpeedBrightness371365
    public static final double Fixed_Palette_Pattern_Heartbeat_Red = -0.25; //Red--Brightness381375
    public static final double Fixed_Palette_Pattern_Heartbeat_Blue = -0.23; //Blue--Brightness391385
    public static final double Fixed_Palette_Pattern_Heartbeat_White = -0.21; //White--Brightness401395
    public static final double Fixed_Palette_Pattern_Heartbeat_Gray = -0.19; //Gray--Brightness411405
    public static final double Fixed_Palette_Pattern_Breath_Red = -0.17; //Red--Brightness421415
    public static final double Fixed_Palette_Pattern_Breath_Blue = -0.15; //Blue--Brightness431425
    public static final double Fixed_Palette_Pattern_Breath_Gray = -0.13; //Gray--Brightness441435
    public static final double Fixed_Palette_Pattern_Strobe_Red = -0.11; //Red--Brightness451445
    public static final double Fixed_Palette_Pattern_Strobe_Blue = 0.9; //Blue--Brightness461455
    public static final double Fixed_Palette_Pattern_Strobe_Gold = 0.7; //Gold--Brightness471465
    public static final double Fixed_Palette_Pattern_Strobe_White = 0.5; //White--Brightness481475
    public static final double Color_1_Pattern_End_to_End_Blend_to_Black_ = 0.3; // Brightness491485
    public static final double Color_1_Pattern_Larson_Scanner_Pattern_Width_Speed_Brightness = 0.1; //501495
    public static final double Color_1_Pattern_Light_Chase_Dimming_Speed_Brightness = 0.01; //511505
    public static final double Color_1_Pattern_Heartbeat_Slow = 0.03; // Brightness521515
    public static final double Color_1_Pattern_Heartbeat_Medium = 0.05; // Brightness531525
    public static final double Color_1_Pattern_Heartbeat_Fast = 0.07; // Brightness541535
    public static final double Color_1_Pattern_Breath_Slow = 0.09; // Brightness551545
    public static final double Color_1_Pattern_Breath_Fast = 0.11; // Brightness561555
    public static final double Color_1_Pattern_Shot = 0.13; // Brightness571565
    public static final double Color_1_Pattern_Strobe = 0.15; // Brightness581575
    public static final double Color_2_Pattern_End_to_End_Blend_to_Black = 0.17; // Brightness591585
    public static final double Color_2_Pattern_Larson_Scanner_Pattern_Width_Speed_Brightnes = 0.19; //601595
    public static final double Color_2_Pattern_Light_Chase_Dimming_Speed_Brightnes = 0.21; //611605
    public static final double Color_2_Pattern_Heartbeat_Slow = 0.23; // Brightness621615
    public static final double Color_2_Pattern_Heartbeat_Medium = 0.25; // Brightness631625
    public static final double Color_2_Pattern_Heartbeat_Fast = 0.27; // Brightness641635
    public static final double Color_2_Pattern_Breath_Slow = 0.29; // Brightness651645
    public static final double Color_2_Pattern_Breath_Fast = 0.31; // Brightness661655
    public static final double Color_2_Pattern_Shot = 0.33; // Brightness671665
    public static final double Color_2_Pattern_Strobe = 0.35; // Brightness681675
    public static final double Color_1_and_2_Pattern_Sparkle_Color_1 = 0.37; //Color_11onColor2-691685
    public static final double Color_1_and_2_Pattern_Sparkle_Color_2 = 0.39; //Color_22onColor1-701695
    public static final double Color_1_and_2_Pattern_Color_Gradient_Color = 0.41; //Color1and2--711705
    public static final double Color_1_and_2_Pattern_Beats_per_Minute_Color = 0.43; //Color1and2PatternDensity721715
    public static final double Color_1_and_2_Pattern_End_to_End_Blend_Color = 0.45; //Color1to2--731725
    public static final double Color_1_and_2_Pattern_End_to_End_Blend_Brightness = 0.47; //Brightness741735
    public static final double Color_1_and_2_Pattern_Color_1_and_Color_2_no_blending = 0.49; //751745
    public static final double Color_1_and_2_Pattern_Twinkles_Color = 0.51; //Color1and2--761755
    public static final double Color_1_and_2_Pattern_Color_Waves_Color = 0.53; //Color1and2--771765
    public static final double Color_1_and_2_Pattern_Sinelon_Color = 0.55; //Color1and2PatternDensity781775
    public static final double Solid_Colors_Hot_Pink = 0.57; //  Brightness791785
    public static final double Solid_Colors_Dark_red = 0.59; //  Brightness801795
    public static final double Solid_Colors_Red = 0.61; //  Brightness811805
    public static final double Solid_Colors_Red_Orange = 0.63; //  Brightness821815
    public static final double Solid_Colors_Orange = 0.65; //  Brightness831825
    public static final double Solid_Colors_Gold = 0.67; //  Brightness841835
    public static final double Solid_Colors_Yellow = 0.69; //  Brightness851845
    public static final double Solid_Colors_Lawn_Green = 0.71; //  Brightness861855
    public static final double Solid_Colors_Lime = 0.73; //  Brightness871865
    public static final double Solid_Colors_Dark_Green = 0.75; //  Brightness881875
    public static final double Solid_Colors_Green = 0.77; //  Brightness891885
    public static final double Solid_Colors_Blue_Green = 0.79; //  Brightness901895
    public static final double Solid_Colors_Aqua = 0.81; //  Brightness911905
    public static final double Solid_Colors_Sky_Blue = 0.83; //  Brightness921915
    public static final double Solid_Colors_Dark_Blue = 0.85; //  Brightness931925
    public static final double Solid_Colors_Blue = 0.87; //  Brightness941935
    public static final double Solid_Colors_Blue_Violet = 0.89; //  Brightness951945
    public static final double Solid_Colors_Violet = 0.91; //  Brightness961955
    public static final double Solid_Colors_White = 0.93; //  Brightness971965
    public static final double Solid_Colors_Gray = 0.95; //  Brightness981975
    public static final double Solid_Colors_Dark_Gray = 0.97; //  Brightness991985
    public static final double Solid_Colors_Black = 0.99; //  Brightness100 199
}
